---
- hosts: server4.abc.com
  remote_user: test
  become: yes
  tasks:
    - name: install nginx
      yum: name=nginx state=installed
    - name: copy index.html
      copy: src=index.html dest=/usr/share/nginx/html
      notify: restart nginx
    - name: start the service
      service: name=nginx state=started
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
