---
- hosts: server4.abc.com
  remote_user: test
  become: yes
  vars:
   pkg: httpd
  vars_files: 
    - abc.yml
  vars_prompt:
    - name: pkg2
      prompt: enter package
  tasks:
    - name: install {{pkg}}
      yum: name={{pkg}} state=installed
    - name: install {{pkg1}}
      yum: name={{pkg1}} state=installed
    - name: install {{pkg2}}
      yum: name={{pkg2}} state=installed
